version: "3.8"

services:
  app:
    image: payments/payments-service
    ports:
      - "8080:8080"
    links:
      - db
      - rabbitmq
    depends_on:
      - db
      - rabbitmq
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=payments
    volumes:
      - postgres_data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data: {}
  rabbitmq_data: {}